Marc/modbus polling
NubeIO/flow-framework pull request #460
Opened 2022-04-29 01:35 UTC by CanuckMarc

@RaiBnod @NubeDev 
This is a tested implementation of modbus with the new polling queue. 

Below are notes regarding the completed tasks and still to complete tasks:

- [ ] - Poll queue adds all points to PriorityPollQueue on modbus plugin enable
- [ ] - QueueUnloader automatically posts the next polling point for each network queue
- [ ] - Polling complete callback works, and re-adds points to the polling queue based on writeMode (with timer)
- [ ] - Poll queue doesn't necessarily keep the points in priority order, but it will always draw the highest priority from the queue first.  
- [ ] - Added another slice to keep track on standby points- eventbus triggers for add remove and update network/device/point
- [ ] - add in a point property that indicates that the point PresentValue should only be updated from the polling (not from the priority array).
- [ ] - add UI selections to model.go in modbus plugin. 
- [ ] - test writeMode types.
- [ ] - add ping check for modbus port availability, otherwise the polling races with failed calls. 
- [ ] - implement a system to promote points to be polled ASAP (on write, or when manually triggered). 
- [ ] - test disable/enable of network/device/point

- [ ]  time.Duration types in settings show up in ns. 
- [ ]  periodically check the polling queue and standby points to check that none have been lost.  
- [ ]  implement checks/monitoring statistics to show if points are not being polled due to short cycling of higher priority points. - - - [ ]  ADD FUNCTION THAT PERIODICALLY CALCULATES STATISTICS.
- [ ]  check that point faults are set and cleared correctly.
- [ ]  test changing of polling priority, poll rate (at device and point level)
- [ ] saving polling queues between enable/disable

- [ ]  FF must update `point.WritePollRequired` to `true`  when there is a value that should be written. 
- [ ]  risk of short cycling error points with higher priority than lower priority points. 

2022-04-30 04:41 UTC, NubeDev commented
these are kinda unsable for defults 
probs best to show the user that they are `ms` if they are aswell

![image](https://user-images.githubusercontent.com/18637436/166091318-61df5442-f50f-469b-95df-59e0e4295cbd.png)

2022-05-01 19:40 UTC, CanuckMarc commented
@NubeDev I got kinda carried away with find and replace on `(i *Instance) --> (inst *Instance)` and ended up changing it throughout FF.  I figured it would be good if it was standardized anyways, but let me know if you want me to undo that commit and just fix the ones in my modbus polling relevant code.

2022-05-01 19:45 UTC, CanuckMarc commented
@NubeDev regarding the polling times, they are currently set in `ns` because that is what GO `time.Duration` types resolve to.  I debated manually changing it to just use seconds and `int` types.  But I think we should probably figure out a way to handle our time input UIs so that it works with `time.Duration` types (as they are easier to understand when work with them in code).  There will be MANY requirements for time based settings, so we should get a UI solution that works well. 

For now, I figured we could just deal with `ns`.  But if the UI improvement would be too delayed, then i'll just switch it up.  Just requires changing some types on the Point/Device/Network models.  Let me know.

2022-05-04 08:07 UTC, NubeDev commented
@RaiBnod 
Can we look at merging this

there is a conflict ill get marc to fix that
@CanuckMarc pls fix

2022-05-04 12:56 UTC, RaiBnod commented on database/point_plugin.go
> +	}
For plugins that are other than "system" and "modbus", they won't find the API to write the value. Coz, other plugins don't have that `PATCH` write API on its plugin.

So, maybe for now we just need to include that `cli.WritePointPlugin(...)` for "modbus".

2022-05-04 12:59 UTC, RaiBnod commented on plugin/nube/protocals/modbus/polling.go
> +			mbClient, err = inst.setClient(net, dev, true)
Creating a client on each loop will be bad. If we are planning to improve this one later, it's all good for now.

2022-05-04 13:00 UTC, RaiBnod commented on database/point_plugin.go
> +}
For plugins that are other than "system" and "modbus", they won't find the API to write the value. Coz, other plugins don't have that `PATCH` write API on its plugin.

So, maybe for now we just need to include that `cli.WritePointPlugin(...)` for "modbus". Or have that write API implemented on other plugins as well.

2022-05-04 13:07 UTC, RaiBnod commented on plugin/nube/protocals/modbus/poll-queue/poll-queue.go
> +}
Seems like this never gets called for fixing the priority-wise unloading. Is this priority-wise unloading is yet to be implemented?

2022-05-04 13:08 UTC, RaiBnod commented on database/point_plugin.go
> +func (d *GormDatabase) WritePointPlugin(uuid string, body *model.Point) (point *model.Point, err error) {
For plugins that are other than "system" and "modbus", they won't find the API to write the value. Coz, other plugins don't have that `PATCH` write API on its plugin.

So, maybe for now we just need to include that `cli.WritePointPlugin(...)` for "modbus". Or have that write API implemented on other plugins as well.

2022-05-04 13:09 UTC, RaiBnod requested changes
I have just gone through the code surfacely and added some of the concerns.

2022-05-04 20:24 UTC, CanuckMarc commented on plugin/nube/protocals/modbus/polling.go
> +			mbClient, err = inst.setClient(net, dev, true)
Noted.  I'll add it to my checklist of items to  be addressed still.

2022-05-04 20:29 UTC, CanuckMarc commented on database/point_plugin.go
> +func (d *GormDatabase) WritePointPlugin(uuid string, body *model.Point) (point *model.Point, err error) {
Good catch.  I'll add default `writePoint` handlers to the other plugins, or add an exception for `modbus`.

2022-05-04 20:51 UTC, CanuckMarc commented
@RaiBnod @NubeDev 

I've updated all the protocol plugins so that `write point` call flows through the plugin before making the DB call.  

I also fixed the merge errors.

2022-05-05 02:30 UTC, RaiBnod commented on plugin/nube/protocals/modbus/poll-queue/poll-manager.go
> +func NewPollManager(dbHandler *dbhandler.Handler, FFNetworkUUID, FFPluginUUID string) *NetworkPollManager {
The variable on go never starts for caps in go, so you better to refactor this: as ffNetworkUUID, ffPluginUUID. I've seen such variables in other places as well.

2022-05-05 02:33 UTC, CanuckMarc commented on plugin/nube/protocals/modbus/poll-queue/poll-manager.go
> +func NewPollManager(dbHandler *dbhandler.Handler, FFNetworkUUID, FFPluginUUID string) *NetworkPollManager {
ok, i'll do that now.  Aidan found one of those the other day too.

2022-05-05 02:36 UTC, RaiBnod commented on plugin/nube/protocals/modbus/poll-queue/poll-manager.go
> +//  - The PollManager Inserts, Removes, and Updates PollingPoints from the PriorityPollQueue based on the settings of the point.  It considers the Network/Device/Point Enables, Point Write-Modes, etc
Please break such comments into multi-lines, the standard is:
- It needs to have codes or comments max till 120 characters in a line

This is because on a small screen. It will be really hard for the readability.

2022-05-05 03:06 UTC, CanuckMarc commented on plugin/nube/protocals/modbus/poll-queue/poll-manager.go
> +func NewPollManager(dbHandler *dbhandler.Handler, FFNetworkUUID, FFPluginUUID string) *NetworkPollManager {
done

2022-05-05 03:06 UTC, CanuckMarc commented on plugin/nube/protocals/modbus/poll-queue/poll-manager.go
> +//  - The PollManager Inserts, Removes, and Updates PollingPoints from the PriorityPollQueue based on the settings of the point.  It considers the Network/Device/Point Enables, Point Write-Modes, etc
removed. and noted.

2022-05-05 03:24 UTC, RaiBnod approved these changes

2022-05-05 03:25 UTC, merged