Add meta tags on network, device and point
NubeIO/flow-framework pull request #748
Opened 2022-11-09 09:33 UTC by enjuthulung

Resolves: #676 

### Summary
- Added meta tags API endpoints for network, device and point
- POST `api/networks/meta_tags/uuid/<network_uuid>` 
- POST `api/devices/meta_tags/uuid/<device_uuid>`
- POST `api/points/meta_tags/uuid/<network_uuid>`
   ```
    -d [
          {
            "key": <key>,
            "value": <value>
         },
          {
            "uuid":<uuid>,
            "key": <key>,
            "value": <value>
         },
      ]
  ```
- Added `with_meta_tags` param in `api/networks?with_meta_tags=true`, `api/devices?with_meta_tags=true` and `api/points?with_meta_tags=true`

2022-11-09 11:32 UTC, RaiBnod commented on router/router.go
> +			networkRoutes.POST("/meta_tags/:uuid", networkHandler.CreateNetworkMetaTags)
To avoid the conflict on routes in the future, make it as `/meta_tags/uuid/:uuid`, so if something comes up in the future like edit from the name it will be `/meta_tags/name/:name`.

Same goes for device and point's metatags.

2022-11-09 11:34 UTC, RaiBnod requested changes
Do a small modification and router to avoid future conflicts.

2022-11-09 15:45 UTC, RaiBnod approved these changes

2022-11-09 15:45 UTC, merged

2022-11-17 03:03 UTC, CanuckMarc commented
@enjuthulung @RaiBnod  

Can you guys please also post how to add classic `tags` (the single value ones).  So ones like `outside`,  or `air`, etc.

2022-11-17 04:09 UTC, RaiBnod commented
> @enjuthulung @RaiBnod
> 
> Can you guys please also post how to add classic `tags` (the single value ones). So ones like `outside`, or `air`, etc.

See this: https://github.com/NubeIO/flow-framework/pull/144#issue-1004540252

2022-11-24 00:39 UTC, CanuckMarc commented
@enjuthulung  I can't make these work either. I tried this:
```
PATCH  192.168.1.10:1616/ff/api/points/meta_tags/uuid/pnt_ac4e227fd5c048fb
DATA:
[
    {
        "key": "hello",
        "value": "world"
    }
]

ALSO TRIED WITH DATA:
[
    {
        "uuid": "pnt_ac4e227fd5c048fb",
        "key": "hello",
        "value": "world"
    }
]

RESPONSE:
{
    "message": "PATCH /api/points/meta_tags/uuid/pnt_ac4e227fd5c048fb [404]: api not found"
}

I also tried with POST (same result).
```

2022-11-24 03:57 UTC, enjuthulung commented
@CanuckMarc please use `PUT`.   [PR](https://github.com/NubeIO/flow-framework/pull/751)
PUT  192.168.1.10:1616/ff/api/points/meta_tags/uuid/pnt_ac4e227fd5c048fb
DATA:
[
    {
        "key": "hello",
        "value": "world"
    }
]